import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

const superNormalize = (t: any) => 
  String(t || '').toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, '');

async function run() {
  console.log('Fetching all records from pagamentos_wix...');
  
  const allRows: any[] = [];
  let page = 0;
  const pageSize = 1000;
  let hasMore = true;
  
  while (hasMore) {
    const { data, error } = await supabase
      .from('pagamentos_wix')
      .select('*')
      .order('created_at', { ascending: true })
      .range(page * pageSize, (page + 1) * pageSize - 1);
      
    if (error) {
      console.error('Error fetching records:', error);
      return;
    }
    
    if (!data || data.length === 0) {
      hasMore = false;
    } else {
      allRows.push(...data);
      if (data.length < pageSize) {
        hasMore = false;
      } else {
        page++;
      }
    }
  }
  
  console.log(`Fetched ${allRows.length} total records.`);
  
  // Group by (aluno_id or email, YYYY-MM, normalized plan name)
  const groups = new Map<string, any[]>();
  
  allRows.forEach(row => {
    const studentOrEmail = row.aluno_id || (row.cobranca_email || '').toLowerCase().trim();
    const date = row.data_pagamento_gmt_03 || row.data_transacao_gmt_03 || '';
    const month = date.substring(0, 7); // YYYY-MM
    const plan = superNormalize(row.produto_nome);
    
    const key = `${studentOrEmail}|${month}|${plan}`;
    const list = groups.get(key) || [];
    list.push(row);
    groups.set(key, list);
  });
  
  const idsToDelete: string[] = [];
  let conflictGroupsCount = 0;
  let falseSuccessCount = 0;
  let duplicateSuccessCount = 0;
  
  groups.forEach((list, key) => {
    if (list.length > 1) {
      conflictGroupsCount++;
      
      // We want to sort the list to prioritize keeping the best record
      // Priority:
      // 1. Wix Payments (CSV) or Wix Webhook with real status
      // 2. Offline/other manual entries
      // 3. Wix API Cron (which is generated by the sync script)
      // Also, if one record is FAILED/RECUSADO/RECUSADA, it's a real failure from the gateway, so it should be kept over a false "Bem-sucedido" from the Cron!
      
      list.sort((a, b) => {
        const isCronA = a.provedor_pagamento === 'Wix API Cron' || String(a.id_provedor_pagamento).includes('-cycle-');
        const isCronB = b.provedor_pagamento === 'Wix API Cron' || String(b.id_provedor_pagamento).includes('-cycle-');
        
        // If one is cron and the other is not, prioritize the non-cron one (keep the non-cron one first)
        if (isCronA && !isCronB) return 1;
        if (!isCronA && isCronB) return -1;
        
        // If both are cron or both are non-cron, keep the one that has a failure status first (it represents the gateway reality)
        const statusA = (a.status_transacao || '').toLowerCase();
        const statusB = (b.status_transacao || '').toLowerCase();
        const isFailA = statusA.includes('falh') || statusA.includes('recus');
        const isFailB = statusB.includes('falh') || statusB.includes('recus');
        
        if (isFailA && !isFailB) return -1;
        if (!isFailA && isFailB) return 1;
        
        // Fallback: keep the oldest one
        return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
      });
      
      const keep = list[0];
      const duplicates = list.slice(1);
      
      console.log(`\nGroup key: ${key}`);
      console.log(`  KEEPING: ID=${keep.id}, Date=${keep.data_pagamento_gmt_03}, Status=${keep.status_transacao}, ProvID=${keep.id_provedor_pagamento}, Source=${keep.provedor_pagamento}`);
      
      duplicates.forEach(dup => {
        const isCron = dup.provedor_pagamento === 'Wix API Cron' || String(dup.id_provedor_pagamento).includes('-cycle-');
        const statusKeep = (keep.status_transacao || '').toLowerCase();
        const statusDup = (dup.status_transacao || '').toLowerCase();
        const isFailKeep = statusKeep.includes('falh') || statusKeep.includes('recus');
        const isFailDup = statusDup.includes('falh') || statusDup.includes('recus');
        
        if (isFailKeep && !isFailDup && isCron) {
          falseSuccessCount++;
          console.log(`  DELETING FALSE SUCCESS: ID=${dup.id}, Date=${dup.data_pagamento_gmt_03}, Status=${dup.status_transacao}, ProvID=${dup.id_provedor_pagamento}, Source=${dup.provedor_pagamento}`);
        } else {
          duplicateSuccessCount++;
          console.log(`  DELETING DUPLICATE: ID=${dup.id}, Date=${dup.data_pagamento_gmt_03}, Status=${dup.status_transacao}, ProvID=${dup.id_provedor_pagamento}, Source=${dup.provedor_pagamento}`);
        }
        idsToDelete.push(dup.id);
      });
    }
  });
  
  console.log(`\nScan complete.`);
  console.log(`Found ${conflictGroupsCount} conflict groups.`);
  console.log(`Found ${falseSuccessCount} false success records to delete.`);
  console.log(`Found ${duplicateSuccessCount} general duplicates to delete.`);
  console.log(`Total records to delete: ${idsToDelete.length}`);
  
  if (idsToDelete.length === 0) {
    console.log('No discrepancies found.');
    return;
  }
  
  // Deletion phase
  console.log('\nDeleting conflicting/duplicate records in batches...');
  const batchSize = 100;
  let deletedCount = 0;
  for (let i = 0; i < idsToDelete.length; i += batchSize) {
    const batch = idsToDelete.slice(i, i + batchSize);
    const { error: delErr } = await supabase
      .from('pagamentos_wix')
      .delete()
      .in('id', batch);
      
    if (delErr) {
      console.error(`Error deleting batch starting at index ${i}:`, delErr);
    } else {
      deletedCount += batch.length;
      console.log(`Deleted ${batch.length} records. (${deletedCount}/${idsToDelete.length})`);
    }
  }
  console.log(`\nCleanup complete. Deleted ${deletedCount} records.`);
}

run();
